name: Run Experiment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/gradle/common-custom-user-data-gradle-plugin"
  GIT_BRANCH: "erichaagdev/temp-task-with-absolute-path"
  TASKS: "assemble"

jobs:
  experiment:
    name: Experiment ${{ matrix.experimentId }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - experimentId: 3
    runs-on: ubuntu-latest
    outputs:
      exp3-results: ${{ steps.fetch-results.outputs.exp3-summary }}
      exp3-summary: ${{ steps.fetch-results.outputs.exp3-summary }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: "temurin"
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/download@actions-stable
        with:
          downloadDevelopmentRelease: true
      - name: Run experiment 3
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-3@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
        with:
          gitBranch: ${{ env.GIT_BRANCH }}
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
      - name: Analyze results
        id: analyze-results
        uses: erichaagdev/gradle-enterprise-oss-projects/.github/actions/summarize-gradle-experiment-results@main
        with:
          develocityApiKey: ${{ secrets.DEVELOCITY_API_KEY }}
          experimentId: ${{ matrix.experimentId }}
          geminiApiKey: ${{ secrets.GEMINI_API_KEY }}
      - name: Print summary
        env:
          SUMMARY: ${{ steps.analyze-results.outputs.summary }}
        run: |
          echo "$SUMMARY"
      - name: Capture summary
        id: capture-summary
        shell: bash
        env:
          EXPERIMENT_ID: ${{ inputs.experimentId }}
          RESULTS: ${{ steps.analyze-results.outputs.results }}
          SUMMARY: ${{ steps.analyze-results.outputs.summary }}
        run: |
          if [[ "$EXPERIMENT_ID" == '3' ]]; then
            echo 'exp3-summary<<EOF' >> $GITHUB_OUTPUT
            echo $SUMMARY >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
            echo 'exp3-results<<EOF' >> $GITHUB_OUTPUT
            echo $RESULTS >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          fi

  analyze:
    runs-on: ubuntu-latest
    needs: experiment
    steps:
      - name: Capture results analysis
        env:
          EXP3_SUMMARY: ${{ steps.analyze.outputs.summary }}
        run: |
          echo "## Experiment 3" >> "$GITHUB_STEP_SUMMARY"
          echo "EXP3_SUMMARY" >> "$GITHUB_STEP_SUMMARY"
