name: Run Experiment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/gradle/common-custom-user-data-gradle-plugin"
  GIT_BRANCH: "erichaagdev/temp-task-with-absolute-path"
  TASKS: "assemble"

jobs:
  experiment:
    name: Experiment ${{ matrix.experimentId }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - experimentId: 2
          - experimentId: 3
    runs-on: ubuntu-latest
    outputs:
      build-scan-exp2: ${{ steps.run-exp2.outputs.buildScanSecondBuild }}
      build-scan-exp3: ${{ steps.run-exp3.outputs.buildScanSecondBuild }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: "temurin"
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/download@actions-stable
        with:
          downloadDevelopmentRelease: true
      - name: Run experiment 2
        id: run-exp2
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-2@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
        with:
          gitBranch: ${{ env.GIT_BRANCH }}
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
        if: matrix.experimentId == 2
      - name: Run experiment 3
        id: run-exp3
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-3@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
        with:
          gitBranch: ${{ env.GIT_BRANCH }}
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
        if: matrix.experimentId == 3

  analyze:
    name: Analyze results
    runs-on: ubuntu-latest
    needs: experiment
    steps:
      - name: Analyze experiment results
        uses: erichaagdev/gradle-enterprise-oss-projects/.github/actions/analyze-gradle-experiment-results@main
        with:
          develocityApiKey: ${{ secrets.DEVELOCITY_API_KEY }}
          geminiApiKey: ${{ secrets.GEMINI_API_KEY }}
          buildScanExperiment2: ${{ needs.experiment.outputs.build-scan-exp2 }}
          buildScanExperiment3: ${{ needs.experiment.outputs.build-scan-exp3 }}
